registerLayout("EDU FM Drum — Board 1", {
  "title": "MKI x ES EDU FM DRUM — Board 1 (VCOs + Waveshaper)",
  "source": "docs/fm_drum_netlist.md",
  "board": "n8synth 6HP",
  "revision": "1.0",
  "notes": "Board 1: DA1 (TL074, normal orientation) with carrier VCO, modulator VCO, carrier CV mixer, waveshaper, impact distortion, click, and pitch envelope. Blocks 4-12 and Block 20 (C9/C10 only). Inter-board: ACC_TRIG, UNACC_TRIG, FM_SW_COM arrive; SINE_OUT, CAR_SCH_OUT, MOD_SCH_OUT, MOD_INT_OUT depart.",

  "_challenges": [
    "DA1 is 14-pin DIP spanning 7 rows (4-10). Carrier on left (A: pins 1-3, B: 5-7), modulator on right (C: 8-10, D: 12-14).",
    "Rows 4-5 (carrier integrator) and 9-10 (modulator integrator) are extremely congested — all 5 holes used per half-row.",
    "R34 (10K) cannot physically span rows 4-22 — split into JW_R34 jumper + short R34 at waveshaper.",
    "Q2.E and Q4.E reset connections routed through Q1.C and Q3.C intermediate rows (11L/11R) because target rows 5/9 are full.",
    "R22/R23 (100K) span 7-8 rows from row 1R to IC pins — at physical limit for axial resistors.",
    "SINE_NODE (row 22L) has 7 connections but only 5 holes — overflow row 34L added via JW_SINE jumper.",
    "Pitch envelope (rows 29-35) distant from CARRIER_CV (row 1) — bridged via R10 + POT1 JPS + inter-board return."
  ],

  "stages": [
    { "id": 1, "name": "IC + Power",
      "desc": "Install DA1 (TL074, normal orientation — pin 1 top-left). Add C9/C10 decoupling caps. Wire VCC, VEE, and GND bus.",
      "test": "Verify +12V on DA1 pin 4 (row 7 col e), -12V on pin 11 (row 7 col f). No signal yet.",
      "color": "#888" },
    { "id": 2, "name": "Carrier VCO",
      "desc": "Integrator (DA1-A: pins 1-3) + Schmitt trigger (DA1-B: pins 5-7) with Q1 NPN current switch. C2 (330pF) integrator cap, R13/R14 CV input, R12 bias, R15 coupling, R16/R17 feedback.",
      "test": "Apply ~5V CV to row 1L (CARRIER_CV). Probe triangle at pin 1 (row 4L), square at pin 7 (row 10L).",
      "color": "#e67e22" },
    { "id": 3, "name": "Carrier VCO Reset",
      "desc": "Q2 NPN bridges C2 on trigger. R20 (1M) bias from UNACC_TRIG bus, R21 (10K) bridge across Q2 C/E.",
      "test": "Send trigger to UNACC_TRIG bus (row 20). Carrier waveform resets phase on each trigger.",
      "color": "#d35400" },
    { "id": 4, "name": "Modulator VCO",
      "desc": "Clone of carrier using DA1-C (pins 8-10) + DA1-D (pins 12-14). C6 (2.2nF) for lower freq range. R25 (100K vs 68K) for wider schmitt thresholds.",
      "test": "Apply ~5V CV to row 1R (MOD_CV). Probe triangle at pin 8 (row 10R), square at pin 14 (row 4R).",
      "color": "#3498db" },
    { "id": 5, "name": "Modulator VCO Reset",
      "desc": "Q4 NPN bridges C6 on trigger. R29 (1M) bias, R30 (10K) bridge.",
      "test": "Trigger should reset modulator waveform phase.",
      "color": "#2980b9" },
    { "id": 6, "name": "Carrier CV Mixer",
      "desc": "R31 (33K) VCC to POT4 top. R33 (33K) POT4 wiper to CARRIER_CV. R32 (100K) FM_SW_COM to CARRIER_CV. D4 clamps CV to GND.",
      "test": "Adjust TUNE CARRIER pot. Carrier frequency should change. FM switch modulates carrier with modulator.",
      "color": "#2ecc71" },
    { "id": 7, "name": "Waveshaper",
      "desc": "R34 (10K) scales carrier triangle. D5/D6 anti-parallel diodes soft-clip into approx sine. R38 (2K) sets diode bias.",
      "test": "Probe SINE_NODE (row 22L). Should see rounded sine wave.",
      "color": "#9b59b6" },
    { "id": 8, "name": "Impact Distortion",
      "desc": "D7 charges C5 (5.6nF) from ACC_TRIG. R51 (2K) discharges. Q6 NPN bridges R34 on accented hits. R36 (470K) pull-up from VCC.",
      "test": "Accented hits have sharper transient and extra harmonics.",
      "color": "#8e44ad" },
    { "id": 9, "name": "Added Click",
      "desc": "D8 isolates UNACC_TRIG. R35 (39K) injects trigger click into SINE_OUT.",
      "test": "Each trigger produces audible click at start of sound.",
      "color": "#e74c3c" },
    { "id": 10, "name": "Pitch Envelope",
      "desc": "R8 (470R) softens attack. D2 charges C4 (470nF). R9 (1K) + POT3 discharge. D3 isolates output. R10 (47K) + POT1 set depth.",
      "test": "Trigger causes pitch sweep downward. TUNE DECAY and TUNE DEPTH control sweep.",
      "color": "#f39c12" }
  ],

  "ics": [
    { "id": "DA1", "value": "TL074", "label": "Carrier VCO (A,B) + Modulator VCO (C,D)", "stage": 1,
      "rotation": 0,
      "pins": [
        { "n": 1,  "r": 4,  "c": "e", "net": "CAR_INT_OUT" },
        { "n": 2,  "r": 5,  "c": "e", "net": "CAR_INT_INV" },
        { "n": 3,  "r": 6,  "c": "e", "net": "CAR_INT_NINV" },
        { "n": 4,  "r": 7,  "c": "e", "net": "VCC" },
        { "n": 5,  "r": 8,  "c": "e", "net": "CAR_SCH_NINV" },
        { "n": 6,  "r": 9,  "c": "e", "net": "CAR_SCH_INV" },
        { "n": 7,  "r": 10, "c": "e", "net": "CAR_SCH_OUT" },
        { "n": 14, "r": 4,  "c": "f", "net": "MOD_SCH_OUT" },
        { "n": 13, "r": 5,  "c": "f", "net": "MOD_SCH_INV" },
        { "n": 12, "r": 6,  "c": "f", "net": "MOD_SCH_NINV" },
        { "n": 11, "r": 7,  "c": "f", "net": "VEE" },
        { "n": 10, "r": 8,  "c": "f", "net": "MOD_INT_NINV" },
        { "n": 9,  "r": 9,  "c": "f", "net": "MOD_INT_INV" },
        { "n": 8,  "r": 10, "c": "f", "net": "MOD_INT_OUT" }
      ]
    }
  ],

  "twoPins": [
    { "id": "C9",  "type": "C", "value": "100nF", "r1": 7,  "c1": "b", "r2": 7,  "c2": "pwrL", "stage": 1,
      "_note": "DA1 VCC decoupling. Pin 4 (row 7L) to pwrL row 7 (odd=GND). Bridges VCC to GND." },
    { "id": "C10", "type": "C", "value": "100nF", "r1": 7,  "c1": "i", "r2": 7,  "c2": "pwrR", "stage": 1,
      "_note": "DA1 VEE decoupling. Pin 11 (row 7R) to pwrR row 7 (odd=GND). Bridges VEE to GND." },

    { "id": "C2",  "type": "C", "value": "330pF",  "r1": 4,  "c1": "c", "r2": 5,  "c2": "c", "stage": 2,
      "_note": "Carrier integrator cap. CAR_INT_OUT (pin 1, row 4L) to CAR_INT_INV (pin 2, row 5L)." },
    { "id": "R13", "type": "R", "value": "100K",   "r1": 1,  "c1": "a", "r2": 5,  "c2": "a", "stage": 2,
      "_note": "CARRIER_CV (row 1L) to CAR_INT_INV (pin 2, row 5L). 4-row span." },
    { "id": "R14", "type": "R", "value": "100K",   "r1": 1,  "c1": "b", "r2": 6,  "c2": "b", "stage": 2,
      "_note": "CARRIER_CV (row 1L) to CAR_INT_NINV (pin 3, row 6L). 5-row span." },
    { "id": "R12", "type": "R", "value": "51K",    "r1": 6,  "c1": "a", "r2": 3,  "c2": "a", "stage": 2,
      "_note": "CAR_INT_NINV (row 6L) to GND bus (row 3L). 3-row span." },
    { "id": "R15", "type": "R", "value": "68K",    "r1": 4,  "c1": "b", "r2": 9,  "c2": "b", "stage": 2,
      "_note": "CAR_INT_OUT (row 4L) to CAR_SCH_INV (pin 6, row 9L). 5-row span." },
    { "id": "R16", "type": "R", "value": "100K",   "r1": 10, "c1": "a", "r2": 8,  "c2": "a", "stage": 2,
      "_note": "CAR_SCH_OUT (row 10L) to CAR_SCH_NINV (pin 5, row 8L). Schmitt feedback." },
    { "id": "R17", "type": "R", "value": "100K",   "r1": 10, "c1": "d", "r2": 5,  "c2": "d", "stage": 2,
      "_note": "CAR_SCH_OUT (row 10L) to CAR_INT_INV (row 5L). Integrator feedback. 5-row span." },

    { "id": "R20", "type": "R", "value": "1M",     "r1": 20, "c1": "b", "r2": 14, "c2": "b", "stage": 3,
      "_note": "UNACC_TRIG (row 20L) to Q2 base (row 14L). Reset bias. 6-row span." },
    { "id": "R21", "type": "R", "value": "10K",    "r1": 15, "c1": "a", "r2": 16, "c2": "a", "stage": 3,
      "_note": "Q2.C (row 15L) to Q2.E (row 16L) bridge resistor. 1-row span." },

    { "id": "C6",  "type": "C", "value": "2.2nF",  "r1": 9,  "c1": "h", "r2": 10, "c2": "h", "stage": 4,
      "_note": "Modulator integrator cap. MOD_INT_INV (pin 9, row 9R) to MOD_INT_OUT (pin 8, row 10R)." },
    { "id": "R22", "type": "R", "value": "100K",   "r1": 1,  "c1": "j", "r2": 9,  "c2": "j", "stage": 4,
      "_note": "MOD_CV (row 1R) to MOD_INT_INV (pin 9, row 9R). 8-row span." },
    { "id": "R23", "type": "R", "value": "100K",   "r1": 1,  "c1": "i", "r2": 8,  "c2": "i", "stage": 4,
      "_note": "MOD_CV (row 1R) to MOD_INT_NINV (pin 10, row 8R). 7-row span." },
    { "id": "R24", "type": "R", "value": "51K",    "r1": 8,  "c1": "j", "r2": 3,  "c2": "j", "stage": 4,
      "_note": "MOD_INT_NINV (row 8R) to GND bus (row 3R). 5-row span." },
    { "id": "R25", "type": "R", "value": "100K",   "r1": 10, "c1": "i", "r2": 5,  "c2": "i", "stage": 4,
      "_note": "MOD_INT_OUT (row 10R) to MOD_SCH_INV (pin 13, row 5R). 5-row span." },
    { "id": "R26", "type": "R", "value": "100K",   "r1": 4,  "c1": "j", "r2": 6,  "c2": "j", "stage": 4,
      "_note": "MOD_SCH_OUT (row 4R) to MOD_SCH_NINV (pin 12, row 6R). Schmitt feedback." },
    { "id": "R27", "type": "R", "value": "100K",   "r1": 4,  "c1": "g", "r2": 9,  "c2": "g", "stage": 4,
      "_note": "MOD_SCH_OUT (row 4R) to MOD_INT_INV (row 9R). Integrator feedback. 5-row span." },

    { "id": "R29", "type": "R", "value": "1M",     "r1": 20, "c1": "j", "r2": 14, "c2": "j", "stage": 5,
      "_note": "UNACC_TRIG (row 20R) to Q4 base (row 14R). Reset bias. 6-row span." },
    { "id": "R30", "type": "R", "value": "10K",    "r1": 15, "c1": "i", "r2": 16, "c2": "i", "stage": 5,
      "_note": "Q4.C (row 15R) to Q4.E (row 16R) bridge resistor. 1-row span." },

    { "id": "R31", "type": "R", "value": "33K",    "r1": 17, "c1": "c", "r2": 18, "c2": "c", "stage": 6,
      "_note": "POT4 top (row 17L) to VCC (row 18L, pwrL even=+12V). Limits max tune voltage." },
    { "id": "R33", "type": "R", "value": "33K",    "r1": 19, "c1": "b", "r2": 17, "c2": "b", "stage": 6,
      "_note": "POT4 wiper (row 19L JPS) to tune limiter node (row 17L). 2-row span." },
    { "id": "R32", "type": "R", "value": "100K",   "r1": 2,  "c1": "g", "r2": 1,  "c2": "c", "stage": 6,
      "_note": "FM_SW_COM (row 2R) to CARRIER_CV (row 1L). Cross-gap via different rows." },
    { "id": "D4",  "type": "D", "value": "1N4148", "r1": 3,  "c1": "d", "r2": 1,  "c2": "d", "stage": 6,
      "_note": "GND (row 3L, anode) to CARRIER_CV (row 1L, cathode). Clamp." },

    { "id": "R34", "type": "R", "value": "10K",    "r1": 21, "c1": "a", "r2": 22, "c2": "a", "stage": 7,
      "_note": "Waveshaper input scaling. CAR_INT_OUT arrives at row 21 via JW_R34 jumper. 1-row span." },
    { "id": "D5",  "type": "D", "value": "1N4148", "r1": 22, "c1": "b", "r2": 23, "c2": "b", "stage": 7,
      "_note": "Anti-parallel diode 1. Anode at SINE_NODE (row 22), cathode row 23." },
    { "id": "D6",  "type": "D", "value": "1N4148", "r1": 23, "c1": "c", "r2": 22, "c2": "c", "stage": 7,
      "_note": "Anti-parallel diode 2 (reverse of D5). Anode row 23, cathode SINE_NODE (row 22)." },
    { "id": "R38", "type": "R", "value": "2K",     "r1": 22, "c1": "d", "r2": 23, "c2": "d", "stage": 7,
      "_note": "SINE_NODE (row 22L) to GND (row 23L, pwrL odd=GND). Diode bias." },

    { "id": "D7",  "type": "D", "value": "1N4148", "r1": 24, "c1": "d", "r2": 25, "c2": "d", "stage": 8,
      "_note": "ACC_TRIG (row 24L, anode) to impact cap node (row 25L, cathode)." },
    { "id": "C5",  "type": "C", "value": "5.6nF",  "r1": 25, "c1": "c", "r2": 26, "c2": "c", "stage": 8,
      "_note": "Impact distortion envelope cap. Row 25 to IMPACT_NODE (row 26)." },
    { "id": "R51", "type": "R", "value": "2K",     "r1": 26, "c1": "b", "r2": 27, "c2": "b", "stage": 8,
      "_note": "IMPACT_NODE (row 26L) to GND (row 27L, pwrL odd=GND). Discharge." },
    { "id": "R36", "type": "R", "value": "470K",   "r1": 26, "c1": "a", "r2": 28, "c2": "a", "stage": 8,
      "_note": "Q6 collector net (row 26L) to VCC (row 28L, pwrL even=+12V). Pull-up." },

    { "id": "D8",  "type": "D", "value": "1N4148", "r1": 20, "c1": "d", "r2": 21, "c2": "d", "stage": 9,
      "_note": "UNACC_TRIG (row 20L, anode) to click node (row 21L, cathode)." },
    { "id": "R35", "type": "R", "value": "39K",    "r1": 21, "c1": "c", "r2": 34, "c2": "b", "stage": 9,
      "_note": "Click node (row 21L) to SINE_NODE overflow (row 34L via JW_SINE). 13-row span." },

    { "id": "R8",  "type": "R", "value": "470",    "r1": 29, "c1": "a", "r2": 30, "c2": "a", "stage": 10,
      "_note": "UNACC_TRIG (row 29L) to D2 anode (row 30L). 1-row span." },
    { "id": "D2",  "type": "D", "value": "1N4148", "r1": 30, "c1": "b", "r2": 31, "c2": "b", "stage": 10,
      "_note": "Charge diode to PITCH_CAP (row 31L)." },
    { "id": "C4",  "type": "C", "value": "470nF",  "r1": 31, "c1": "a", "r2": 31, "c2": "g", "stage": 10,
      "_note": "PITCH_CAP (row 31L) to GND (row 31R, pwrR odd=GND). Film cap crosses center gap." },
    { "id": "R9",  "type": "R", "value": "1K",     "r1": 31, "c1": "d", "r2": 32, "c2": "d", "stage": 10,
      "_note": "PITCH_CAP (row 31L) to POT3 path (row 32L). Min discharge." },
    { "id": "D3",  "type": "D", "value": "1N4148", "r1": 31, "c1": "c", "r2": 33, "c2": "c", "stage": 10,
      "_note": "PITCH_CAP (row 31L, anode) to PITCH_OUT (row 33L, cathode). Isolation." },
    { "id": "R10", "type": "R", "value": "47K",    "r1": 33, "c1": "a", "r2": 35, "c2": "a", "stage": 10,
      "_note": "PITCH_OUT (row 33L) to POT1 path (row 35L JPS). 2-row span." }
  ],

  "transistors": [
    { "id": "Q1", "subtype": "NPN", "value": "BC548", "eR": 13, "eC": "c", "bR": 12, "bC": "c", "cR": 11, "cC": "c", "stage": 2,
      "_note": "Carrier VCO NPN. E to GND (pwrL r13). B from CAR_SCH_OUT via JW2. C to CAR_INT_INV via JW1." },
    { "id": "Q2", "subtype": "NPN", "value": "BC548", "eR": 16, "eC": "d", "bR": 14, "bC": "d", "cR": 15, "cC": "d", "stage": 3,
      "_note": "Carrier reset NPN. B from R20. C to CAR_INT_OUT via JW3. E to CAR_INT_INV via JW4. R21 bridges C/E." },
    { "id": "Q3", "subtype": "NPN", "value": "BC548", "eR": 13, "eC": "h", "bR": 12, "bC": "h", "cR": 11, "cC": "h", "stage": 4,
      "_note": "Modulator VCO NPN. E to GND (pwrR r13). B from MOD_SCH_OUT via JW6. C to MOD_INT_INV via JW7." },
    { "id": "Q4", "subtype": "NPN", "value": "BC548", "eR": 16, "eC": "g", "bR": 14, "bC": "g", "cR": 15, "cC": "g", "stage": 5,
      "_note": "Modulator reset NPN. B from R29. C to MOD_INT_OUT via JW8. E to MOD_INT_INV via JW9. R30 bridges C/E." },
    { "id": "Q6", "subtype": "NPN", "value": "BC548", "eR": 26, "eC": "e", "bR": 25, "bC": "e", "cR": 24, "cC": "e", "stage": 8,
      "_note": "Impact NPN. B from IMPACT_NODE (C5). C to SINE_NODE via JW11. E to R34 input via JW12." }
  ],

  "jumpers": [
    { "id": "JW1",  "r1": 11, "c1": "b", "r2": 5,  "c2": "b", "label": "Q1.C to CAR_INT_INV", "stage": 2,
      "_note": "Q1 collector net (row 11L) to CAR_INT_INV (pin 2, row 5L). 6-row span." },
    { "id": "JW2",  "r1": 10, "c1": "c", "r2": 12, "c2": "d", "label": "CAR_SCH_OUT to Q1.B", "stage": 2,
      "_note": "CAR_SCH_OUT (pin 7, row 10L) to Q1 base net (row 12L). 2-row span." },
    { "id": "JW3",  "r1": 15, "c1": "c", "r2": 4,  "c2": "a", "label": "Q2.C to CAR_INT_OUT", "stage": 3,
      "_note": "Q2 collector net (row 15L) to CAR_INT_OUT (pin 1, row 4L). 11-row span." },
    { "id": "JW4",  "r1": 16, "c1": "c", "r2": 11, "c2": "a", "label": "Q2.E to CAR_INT_INV", "stage": 3,
      "_note": "Q2 emitter net (row 16L) to CAR_INT_INV net via row 11L (joined by JW1). 5-row span." },
    { "id": "JW5",  "r1": 20, "c1": "h", "r2": 20, "c2": "e", "label": "UNACC_TRIG L-R bridge", "stage": 3,
      "_note": "Bridges UNACC_TRIG from right side (R29 at row 20R) to left side (R20/D8/pitch). Row 20 cross-gap." },
    { "id": "JW6",  "r1": 4,  "c1": "h", "r2": 12, "c2": "i", "label": "MOD_SCH_OUT to Q3.B", "stage": 4,
      "_note": "MOD_SCH_OUT (pin 14, row 4R) to Q3 base net (row 12R). 8-row span." },
    { "id": "JW7",  "r1": 11, "c1": "i", "r2": 9,  "c2": "i", "label": "Q3.C to MOD_INT_INV", "stage": 4,
      "_note": "Q3 collector net (row 11R) to MOD_INT_INV (pin 9, row 9R). 2-row span." },
    { "id": "JW8",  "r1": 15, "c1": "h", "r2": 10, "c2": "g", "label": "Q4.C to MOD_INT_OUT", "stage": 5,
      "_note": "Q4 collector net (row 15R) to MOD_INT_OUT (pin 8, row 10R). 5-row span." },
    { "id": "JW9",  "r1": 16, "c1": "h", "r2": 11, "c2": "j", "label": "Q4.E to MOD_INT_INV", "stage": 5,
      "_note": "Q4 emitter net (row 16R) to MOD_INT_INV net via row 11R (joined by Q3.C/JW7). 5-row span." },
    { "id": "JW10", "r1": 17, "c1": "a", "r2": 1,  "c2": "e", "label": "TUNE_MIX to CARRIER_CV", "stage": 6,
      "_note": "Tune limiter (row 17L) to CARRIER_CV (row 1L, IC pin 1 side). 16-row span." },
    { "id": "JW_R34","r1": 4,  "c1": "d", "r2": 21, "c2": "b", "label": "CAR_INT_OUT to R34", "stage": 7,
      "_note": "Jumper from CAR_INT_OUT (pin 1, row 4L) to R34 input (row 21L). 17-row span." },
    { "id": "JW_SINE","r1": 22, "c1": "e", "r2": 34, "c2": "a", "label": "SINE_NODE overflow", "stage": 7,
      "_note": "Extends SINE_NODE from row 22L to overflow row 34L for Q6.C, R35, and SINE_OUT departure." },
    { "id": "JW11", "r1": 24, "c1": "c", "r2": 34, "c2": "c", "label": "Q6.C to SINE_NODE", "stage": 8,
      "_note": "Q6 collector (row 24L) to SINE_NODE overflow (row 34L). 10-row span." },
    { "id": "JW12", "r1": 26, "c1": "d", "r2": 21, "c2": "e", "label": "Q6.E to R34 input", "stage": 8,
      "_note": "Q6 emitter net (row 26L) to R34 input side (row 21L, CAR_INT_OUT net). 5-row span." },
    { "id": "JW13", "r1": 20, "c1": "c", "r2": 29, "c2": "b", "label": "UNACC_TRIG to Pitch", "stage": 10,
      "_note": "UNACC_TRIG (row 20L) to pitch envelope R8 input (row 29L). 9-row span." },
    { "id": "JW14", "r1": 10, "c1": "b", "r2": 36, "c2": "a", "label": "CAR_SCH_OUT to Bd2", "stage": 2,
      "_note": "Carrier square wave (pin 7, row 10L) to board edge (row 36) for board 2 XOR." },
    { "id": "JW15", "r1": 4,  "c1": "i", "r2": 36, "c2": "b", "label": "MOD_SCH_OUT to Bd2", "stage": 4,
      "_note": "Modulator square wave (pin 14, row 4R) to board edge (row 36) for board 2 XOR." },
    { "id": "JW16", "r1": 10, "c1": "j", "r2": 2,  "c2": "h", "label": "MOD_INT_OUT to FM_SW", "stage": 4,
      "_note": "Modulator triangle (pin 8, row 10R) to FM switch path (row 2R). Departs to board 2." },
    { "id": "JW17", "r1": 34, "c1": "d", "r2": 36, "c2": "c", "label": "SINE_OUT to Bd2", "stage": 7,
      "_note": "SINE_NODE overflow (row 34L) to board edge (row 36) for board 2 VCA." }
  ],

  "powerWires": [
    { "r1": 7,  "c1": "a", "r2": 8,  "c2": "pwrL", "label": "DA1 VCC",     "stage": 1,
      "_note": "Pin 4 (VCC, row 7L) to pwrL row 8 (even=+12V)" },
    { "r1": 7,  "c1": "j", "r2": 8,  "c2": "pwrR", "label": "DA1 VEE",     "stage": 1,
      "_note": "Pin 11 (VEE, row 7R) to pwrR row 8 (even=-12V)" },
    { "r1": 3,  "c1": "c", "r2": 3,  "c2": "pwrL", "label": "GND bus L",   "stage": 1,
      "_note": "Row 3L GND bus to pwrL row 3 (odd=GND)" },
    { "r1": 3,  "c1": "h", "r2": 3,  "c2": "pwrR", "label": "GND bus R",   "stage": 1,
      "_note": "Row 3R GND bus to pwrR row 3 (odd=GND)" },
    { "r1": 13, "c1": "b", "r2": 13, "c2": "pwrL", "label": "Q1.E GND",    "stage": 2,
      "_note": "Q1 emitter net (row 13L) to GND (pwrL row 13, odd=GND)" },
    { "r1": 13, "c1": "g", "r2": 13, "c2": "pwrR", "label": "Q3.E GND",    "stage": 4,
      "_note": "Q3 emitter net (row 13R) to GND (pwrR row 13, odd=GND)" },
    { "r1": 23, "c1": "a", "r2": 23, "c2": "pwrL", "label": "WS GND",      "stage": 7,
      "_note": "Waveshaper R38 GND (row 23L) to pwrL row 23 (odd=GND)" },
    { "r1": 27, "c1": "a", "r2": 27, "c2": "pwrL", "label": "Impact GND",  "stage": 8,
      "_note": "R51 GND (row 27L) to pwrL row 27 (odd=GND)" },
    { "r1": 28, "c1": "b", "r2": 28, "c2": "pwrL", "label": "R36 VCC",     "stage": 8,
      "_note": "R36 VCC end (row 28L) to pwrL row 28 (even=+12V)" },
    { "r1": 18, "c1": "b", "r2": 18, "c2": "pwrL", "label": "R31 VCC",     "stage": 6,
      "_note": "R31 VCC end (row 18L) to pwrL row 18 (even=+12V)" },
    { "r1": 31, "c1": "h", "r2": 31, "c2": "pwrR", "label": "C4 GND",      "stage": 10,
      "_note": "C4 GND side (row 31R) to pwrR row 31 (odd=GND)" },
    { "r1": 32, "c1": "b", "r2": 33, "c2": "pwrL", "label": "R9 disch GND", "stage": 10,
      "_note": "R9/POT3 discharge (row 32L) to GND via pwrL row 33 (odd=GND)" }
  ],

  "jpsWires": [
    { "id": "POT4.1", "label": "TUNE CARRIER top",     "row": 17, "col": "d", "stage": 6,
      "_note": "POT4 pin 1. R31 connects VCC to this node via 33K." },
    { "id": "POT4.w", "label": "TUNE CARRIER wiper",   "row": 19, "col": "a", "stage": 6,
      "_note": "POT4 wiper. R33 connects this to tune limiter node (row 17L)." },
    { "id": "FM_SW",  "label": "FM switch COM",        "row": 2,  "col": "j", "stage": 6,
      "_note": "FM_SW_COM from board 2. R32 connects to CARRIER_CV." },
    { "id": "ACC_TRIG", "label": "ACC_TRIG in",        "row": 24, "col": "a", "stage": 8,
      "_note": "Accented trigger from board 2. Feeds D7 for impact distortion." },
    { "id": "UNACC_TRIG", "label": "UNACC_TRIG in",   "row": 20, "col": "a", "stage": 9,
      "_note": "Unaccented trigger from board 2. Feeds click (D8) and pitch envelope." },
    { "id": "POT3.w", "label": "TUNE DECAY wiper",     "row": 32, "col": "c", "stage": 10,
      "_note": "POT3 wiper. R9 to POT3 to GND controls pitch envelope discharge." },
    { "id": "POT1.1", "label": "TUNE DEPTH pin1",      "row": 35, "col": "b", "stage": 10,
      "_note": "POT1 pin 1. R10 feeds PITCH_OUT here." },
    { "id": "POT1.w", "label": "TUNE DEPTH wiper",     "row": 35, "col": "c", "stage": 10,
      "_note": "POT1 wiper output to CARRIER_CV via inter-board return." },
    { "id": "MOD_CV",  "label": "MOD_CV pot in",       "row": 1,  "col": "h", "stage": 4,
      "_note": "Modulator tune pot signal from board 2 tune CV network." }
  ],

  "netLabels": [
    { "r": 1,  "side": "L", "name": "CARRIER_CV",         "stage": 2 },
    { "r": 1,  "side": "R", "name": "MOD_CV",             "stage": 4 },
    { "r": 2,  "side": "R", "name": "FM_SW_COM",          "stage": 6 },
    { "r": 3,  "side": "L", "name": "GND bus",            "stage": 1 },
    { "r": 3,  "side": "R", "name": "GND bus",            "stage": 1 },
    { "r": 4,  "side": "L", "name": "CAR_INT_OUT (p1)",   "stage": 2 },
    { "r": 4,  "side": "R", "name": "MOD_SCH_OUT (p14)",  "stage": 4 },
    { "r": 5,  "side": "L", "name": "CAR_INT_INV (p2)",   "stage": 2 },
    { "r": 5,  "side": "R", "name": "MOD_SCH_INV (p13)",  "stage": 4 },
    { "r": 6,  "side": "L", "name": "CAR_INT_NINV (p3)",  "stage": 2 },
    { "r": 6,  "side": "R", "name": "MOD_SCH_NINV (p12)", "stage": 4 },
    { "r": 7,  "side": "L", "name": "VCC (p4)",           "stage": 1 },
    { "r": 7,  "side": "R", "name": "VEE (p11)",          "stage": 1 },
    { "r": 8,  "side": "L", "name": "CAR_SCH_NINV (p5)",  "stage": 2 },
    { "r": 8,  "side": "R", "name": "MOD_INT_NINV (p10)", "stage": 4 },
    { "r": 9,  "side": "L", "name": "CAR_SCH_INV (p6)",   "stage": 2 },
    { "r": 9,  "side": "R", "name": "MOD_INT_INV (p9)",   "stage": 4 },
    { "r": 10, "side": "L", "name": "CAR_SCH_OUT (p7)",   "stage": 2 },
    { "r": 10, "side": "R", "name": "MOD_INT_OUT (p8)",   "stage": 4 },
    { "r": 11, "side": "L", "name": "Q1.C / INT_INV",     "stage": 2 },
    { "r": 11, "side": "R", "name": "Q3.C / INT_INV",     "stage": 4 },
    { "r": 12, "side": "L", "name": "Q1.B",               "stage": 2 },
    { "r": 12, "side": "R", "name": "Q3.B",               "stage": 4 },
    { "r": 13, "side": "L", "name": "Q1.E (GND)",         "stage": 2 },
    { "r": 13, "side": "R", "name": "Q3.E (GND)",         "stage": 4 },
    { "r": 14, "side": "L", "name": "Q2.B (reset)",       "stage": 3 },
    { "r": 14, "side": "R", "name": "Q4.B (reset)",       "stage": 5 },
    { "r": 15, "side": "L", "name": "Q2.C",               "stage": 3 },
    { "r": 15, "side": "R", "name": "Q4.C",               "stage": 5 },
    { "r": 16, "side": "L", "name": "Q2.E",               "stage": 3 },
    { "r": 16, "side": "R", "name": "Q4.E",               "stage": 5 },
    { "r": 17, "side": "L", "name": "TUNE_MIX",           "stage": 6 },
    { "r": 18, "side": "L", "name": "R31 VCC",            "stage": 6 },
    { "r": 19, "side": "L", "name": "POT4 wiper",         "stage": 6 },
    { "r": 20, "side": "L", "name": "UNACC_TRIG",         "stage": 9 },
    { "r": 21, "side": "L", "name": "R34_IN / CLICK",     "stage": 7 },
    { "r": 22, "side": "L", "name": "SINE_NODE",          "stage": 7 },
    { "r": 23, "side": "L", "name": "WS GND",             "stage": 7 },
    { "r": 24, "side": "L", "name": "ACC_TRIG / Q6.C",    "stage": 8 },
    { "r": 25, "side": "L", "name": "IMPACT cap / Q6.B",  "stage": 8 },
    { "r": 26, "side": "L", "name": "IMPACT_NODE / Q6.E", "stage": 8 },
    { "r": 27, "side": "L", "name": "R51 GND",            "stage": 8 },
    { "r": 28, "side": "L", "name": "R36 VCC",            "stage": 8 },
    { "r": 29, "side": "L", "name": "Pitch R8 in",        "stage": 10 },
    { "r": 30, "side": "L", "name": "Pitch D2 jcn",       "stage": 10 },
    { "r": 31, "side": "L", "name": "PITCH_CAP",          "stage": 10 },
    { "r": 32, "side": "L", "name": "R9/POT3",            "stage": 10 },
    { "r": 33, "side": "L", "name": "PITCH_OUT",          "stage": 10 },
    { "r": 34, "side": "L", "name": "SINE_NODE (overflow)","stage": 7 },
    { "r": 35, "side": "L", "name": "POT1 DEPTH",         "stage": 10 },
    { "r": 36, "side": "L", "name": "to Board 2",         "stage": 1 }
  ]
}
);
