registerLayout("EDU FM Drum — Board 2", {
  "title": "MKI x ES EDU FM DRUM — Board 2 (Trigger + VCA + XOR + HPF)",
  "source": "docs/fm_drum_netlist.md",
  "board": "n8synth 10HP",
  "revision": "1.0",
  "notes": "Board 2 of 2. DA2 (TL072, rotated 180°) handles gate-to-trigger comparator (A) and VCA (B). Also: accent CV, decay envelope, XOR pulse gate, Sallen-Key HPF, sine/pulse + FM switches, tune CV. Inter-board signals from Board 1: SINE_OUT, CAR_SQ, MOD_SQ, MOD_TRI, UNACC_TRIG. No C14 (47uF electrolytic) — user handles power conditioning.",

  "_challenges": [
    "DA2 is 8-pin DIP rotated 180°. VCA (section B) on left pins 5-7, comparator (section A) on right pins 1-3.",
    "R3 (100K VCC→pin 2) needs +12V routed to right side — jumper from DA2 VCC row 7L across to row 8R.",
    "Q5 (VCA NPN) collector must reach DA2 pin 6 (row 5L) — long jumper from row 30.",
    "XOR gate (4 diodes + PNP) needs CAR_SQ and MOD_SQ from row 1L via long jumpers.",
    "Decay envelope (row 14L) driven by ACC_TRIG (row 12R) — cross-sides jumper.",
    "Tune CV PNP pair (Q12/Q13) share base node but separate emitters — routed on row 35-36.",
    "SINE_OUT arrives from Board 1 at row 1L and must reach switch area at row 27 — long jumper.",
    "VCA_OUT (pin 7, row 6L) must reach output jack at row 33 — jumper across gap + down."
  ],

  "stages": [
    { "id": 1, "name": "ICs + Power",
      "desc": "Install DA2 (TL072 rotated 180°) rows 4-7. Add decoupling caps C11 and C12. Wire IC power pins to rails and establish GND bus at row 3.",
      "test": "Verify +12V on DA2 pin 8 (row 7 col e), -12V on pin 4 (row 4 col f). No signal yet.",
      "color": "#888" },
    { "id": 2, "name": "Gate-to-Trigger",
      "desc": "HP filter (C1/R1) differentiates gate edge. Comparator (DA2-A) with R3/R2 threshold and R5 hysteresis converts to clean trigger pulse.",
      "test": "Inject gate at J1 (row 1R). Probe COMP_OUT (row 7R) for sharp +12V trigger pulse.",
      "color": "#e74c3c" },
    { "id": 3, "name": "Accent CV",
      "desc": "R6 feeds COMP_OUT to accent node. Q9 (PNP) sets floor from accent CV. Q8 (NPN) buffers output as ACC_TRIG.",
      "test": "ACC_TRIG amplitude varies with accent CV jack voltage. UNACC_TRIG at row 7R is full amplitude.",
      "color": "#c0392b" },
    { "id": 4, "name": "Decay Envelope",
      "desc": "D1 charges C3 (1uF electrolytic) from ACC_TRIG. POT2 + R7 control discharge rate.",
      "test": "Exponential decay on DECAY_CAP (row 14L) after each trigger.",
      "color": "#f39c12" },
    { "id": 5, "name": "Decay CV",
      "desc": "Q11 (PNP) sets voltage floor on decay cap. R50 (470K) bypass allows gradual full discharge.",
      "test": "Higher decay CV at J3 = shorter effective decay time.",
      "color": "#e67e22" },
    { "id": 6, "name": "XOR Pulse Gate",
      "desc": "Discrete XOR from 4 diodes (D9-D12) + PNP (Q10). Carrier + modulator squares produce ring-mod pulse.",
      "test": "Metallic/chaotic pulse at XOR_OUT (row 20L).",
      "color": "#9b59b6" },
    { "id": 7, "name": "High Pass Filter",
      "desc": "Sallen-Key HPF (C7/C15/R44) with NPN follower (Q7). ~7.5kHz cutoff. C8 blocks DC on output.",
      "test": "Only high frequencies at HPF_OUT (row 25R). Low frequencies attenuated.",
      "color": "#8e44ad" },
    { "id": 8, "name": "Sine/Pulse Switch",
      "desc": "SW2 (SPDT on control deck) selects sine or HPF pulse as VCA input. R37 (18K) scales pulse level.",
      "test": "SW2 toggles between warm sine and harsh pulse character.",
      "color": "#2ecc71" },
    { "id": 9, "name": "VCA + Output",
      "desc": "Q5 (NPN) as voltage-controlled resistor at DA2-B inverting input. R39 feedback, RV1 (2M) trimmer nulls DC offset. J5 output.",
      "test": "Drum sound at OUTPUT jack. Trim RV1 for zero DC at idle.",
      "color": "#3498db" },
    { "id": 10, "name": "FM Switch",
      "desc": "SW1 (SPDT on control deck) routes modulator triangle or GND to carrier CV mixer on Board 1.",
      "test": "SW1 ON: FM modulation audible. OFF: pure tone.",
      "color": "#27ae60" },
    { "id": 11, "name": "Tune CV",
      "desc": "R48/R49 attenuate external CV + POT6 into D13 → PNP pair (Q12/Q13) shifts both tune pot grounds.",
      "test": "Tune CV jack changes carrier + modulator pitch together.",
      "color": "#1abc9c" }
  ],

  "ics": [
    { "id": "DA2", "value": "TL072", "label": "Comparator + VCA", "stage": 1,
      "rotation": 180,
      "pins": [
        { "n": 5, "r": 4, "c": "e", "net": "VCA_NINV" },
        { "n": 4, "r": 4, "c": "f", "net": "VEE" },
        { "n": 6, "r": 5, "c": "e", "net": "VCA_INV" },
        { "n": 3, "r": 5, "c": "f", "net": "COMP_NINV" },
        { "n": 7, "r": 6, "c": "e", "net": "VCA_OUT" },
        { "n": 2, "r": 6, "c": "f", "net": "COMP_INV" },
        { "n": 8, "r": 7, "c": "e", "net": "VCC" },
        { "n": 1, "r": 7, "c": "f", "net": "COMP_OUT" }
      ]
    }
  ],

  "twoPins": [
    { "id": "C11", "type": "C", "value": "100nF", "r1": 7, "c1": "a", "r2": 7, "c2": "pwrL", "stage": 1,
      "_note": "DA2 VCC decoupling. Pin 8 net (row 7L) to pwrL row 7 (odd=GND). Bridges VCC to GND." },
    { "id": "C12", "type": "C", "value": "100nF", "r1": 4, "c1": "g", "r2": 5, "c2": "pwrR", "stage": 1,
      "_note": "DA2 VEE decoupling. Pin 4 net (row 4R) to pwrR row 5 (odd=GND). Bridges VEE to GND." },

    { "id": "C1",  "type": "C", "value": "10nF",  "r1": 1, "c1": "h", "r2": 2, "c2": "h", "stage": 2,
      "_note": "GATE_IN (row 1R) to HP_OUT (row 2R). HP coupling cap." },
    { "id": "R1",  "type": "R", "value": "39K",   "r1": 2, "c1": "i", "r2": 3, "c2": "i", "stage": 2,
      "_note": "HP_OUT (row 2R) to GND bus (row 3R). HP discharge." },
    { "id": "R4",  "type": "R", "value": "10K",   "r1": 2, "c1": "j", "r2": 5, "c2": "j", "stage": 2,
      "_note": "HP_OUT (row 2R) to DA2 pin 3 COMP+ (row 5R). Signal to comparator non-inv." },
    { "id": "R2",  "type": "R", "value": "5K6",   "r1": 5, "c1": "g", "r2": 3, "c2": "g", "stage": 2,
      "_note": "DA2 pin 3 COMP+ (row 5R) to GND bus (row 3R). Threshold reference divider bottom." },
    { "id": "R3",  "type": "R", "value": "100K",  "r1": 8, "c1": "h", "r2": 6, "c2": "h", "stage": 2,
      "_note": "VCC (row 8R, via JW1 jumper from row 7L) to DA2 pin 2 COMP_INV (row 6R). Threshold top." },
    { "id": "R5",  "type": "R", "value": "33K",   "r1": 7, "c1": "h", "r2": 5, "c2": "i", "stage": 2,
      "_note": "COMP_OUT (pin 1, row 7R) to COMP+ (pin 3, row 5R). Positive feedback for hysteresis." },

    { "id": "R6",  "type": "R", "value": "100K",  "r1": 7, "c1": "j", "r2": 10, "c2": "j", "stage": 3,
      "_note": "COMP_OUT (pin 1, row 7R) to ACC_NODE (row 10R). Trigger to accent network." },

    { "id": "D1",  "type": "D", "value": "1N4148", "r1": 13, "c1": "a", "r2": 14, "c2": "a", "stage": 4,
      "_note": "ACC_TRIG (row 13L, anode) to DECAY_CAP (row 14L, cathode). Charge diode." },
    { "id": "C3",  "type": "C", "value": "1uF",   "r1": 14, "c1": "b", "r2": 15, "c2": "b", "stage": 4,
      "_note": "DECAY_CAP (row 14L) to GND (row 15L odd). Electrolytic, +leg row 14. Observe polarity." },
    { "id": "R7",  "type": "R", "value": "4K7",   "r1": 14, "c1": "c", "r2": 16, "c2": "c", "stage": 4,
      "_note": "DECAY_CAP to POT2 path. Min discharge resistor. Row 16 connects to DECAY pot wiper JPS." },

    { "id": "R50", "type": "R", "value": "470K",  "r1": 14, "c1": "d", "r2": 15, "c2": "d", "stage": 5,
      "_note": "DECAY_CAP (row 14L) to GND (row 15L odd). Slow bypass discharge past CV floor." },

    { "id": "D9",  "type": "D", "value": "1N4148", "r1": 17, "c1": "a", "r2": 18, "c2": "a", "stage": 6,
      "_note": "CAR_SQ (row 17L via JW4, anode) to Q10.E node (row 18L, cathode)." },
    { "id": "D10", "type": "D", "value": "1N4148", "r1": 19, "c1": "a", "r2": 17, "c2": "b", "stage": 6,
      "_note": "Q10.B node (row 19L, anode) to CAR_SQ node (row 17L, cathode). Cross-connected." },
    { "id": "D11", "type": "D", "value": "1N4148", "r1": 18, "c1": "b", "r2": 17, "c2": "c", "stage": 6,
      "_note": "Q10.E node (row 18L, anode) to MOD_SQ node (row 17L col c, cathode). Via JW5 from row 2L." },
    { "id": "D12", "type": "D", "value": "1N4148", "r1": 17, "c1": "d", "r2": 19, "c2": "d", "stage": 6,
      "_note": "MOD_SQ node (row 17L, anode) to Q10.B node (row 19L, cathode)." },
    { "id": "R43", "type": "R", "value": "100K",  "r1": 18, "c1": "c", "r2": 19, "c2": "c", "stage": 6,
      "_note": "Q10.E (row 18L) to Q10.B (row 19L). Bias resistor." },
    { "id": "R45", "type": "R", "value": "10K",   "r1": 20, "c1": "a", "r2": 21, "c2": "pwrL", "stage": 6,
      "_note": "XOR_OUT (row 20L from Q10.C) to GND (pwrL row 21, odd=GND). Output pull-down." },

    { "id": "C7",  "type": "C", "value": "470pF", "r1": 20, "c1": "b", "r2": 22, "c2": "b", "stage": 7,
      "_note": "XOR_OUT (row 20L) to HPF_NODE_A (row 22L). HPF input cap 1." },
    { "id": "C15", "type": "C", "value": "470pF", "r1": 22, "c1": "c", "r2": 23, "c2": "c", "stage": 7,
      "_note": "HPF_NODE_A (row 22L) to Q7.B (row 23L). HPF cap 2." },
    { "id": "R44", "type": "R", "value": "100K",  "r1": 22, "c1": "d", "r2": 24, "c2": "d", "stage": 7,
      "_note": "HPF_NODE_A (row 22L) to Q7.E (row 24L). Sallen-Key feedback path." },
    { "id": "R46", "type": "R", "value": "10K",   "r1": 24, "c1": "b", "r2": 25, "c2": "b", "stage": 7,
      "_note": "HPF_EMIT (row 24L) to VEE_BIAS midpoint (row 25L). Emitter bias top half." },
    { "id": "R47", "type": "R", "value": "10K",   "r1": 25, "c1": "a", "r2": 26, "c2": "a", "stage": 7,
      "_note": "VEE_BIAS midpoint (row 25L) to VEE node (row 26L). Emitter bias bottom half." },
    { "id": "C8",  "type": "C", "value": "15nF",  "r1": 24, "c1": "a", "r2": 25, "c2": "g", "stage": 7,
      "_note": "HPF_EMIT (row 24L) to HPF_OUT (row 25R). DC-blocking output cap. Crosses center gap." },

    { "id": "R37", "type": "R", "value": "18K",   "r1": 25, "c1": "h", "r2": 27, "c2": "h", "stage": 8,
      "_note": "HPF_OUT (row 25R) to SW2 pulse terminal (row 27R). Pulse input scaling." },

    { "id": "R40", "type": "R", "value": "47",    "r1": 27, "c1": "a", "r2": 28, "c2": "a", "stage": 9,
      "_note": "TYPE_SW_COM (row 27L from switch JPS) to VCA_BASE_NODE (row 28L). Coupling to Q5 base." },
    { "id": "R41", "type": "R", "value": "470K",  "r1": 30, "c1": "a", "r2": 31, "c2": "pwrL", "stage": 9,
      "_note": "Q5.E (row 30L) to GND (pwrL row 31, odd=GND). VCA emitter bias." },
    { "id": "R39", "type": "R", "value": "200K",  "r1": 6, "c1": "a", "r2": 5, "c2": "a", "stage": 9,
      "_note": "VCA_OUT (DA2 pin 7, row 6L) to VCA_INV (DA2 pin 6, row 5L). Feedback resistor." },
    { "id": "RV1", "type": "TRIM", "value": "2M", "r1": 5, "c1": "b", "r2": 32, "c2": "b", "stage": 9,
      "_note": "VCA_INV (pin 6, row 5L) to RV1 wiper (row 32L). DC offset trim. Long span." },
    { "id": "R42", "type": "R", "value": "1M",    "r1": 32, "c1": "a", "r2": 33, "c2": "pwrL", "stage": 9,
      "_note": "RV1 wiper (row 32L) to GND (pwrL row 33, odd=GND). Trim baseline resistor." },

    { "id": "R48", "type": "R", "value": "330K",  "r1": 34, "c1": "h", "r2": 35, "c2": "h", "stage": 11,
      "_note": "TUNE_CV_IN (row 34R from J4 JPS) to TUNE_CV_ATT node (row 35R). Input attenuator." },
    { "id": "R49", "type": "R", "value": "100K",  "r1": 34, "c1": "i", "r2": 35, "c2": "i", "stage": 11,
      "_note": "POT6 wiper (row 34R JPS) to TUNE_CV_ATT (row 35R). Tune CV INT pot mixing." },
    { "id": "D13", "type": "D", "value": "1N4148", "r1": 35, "c1": "j", "r2": 36, "c2": "j", "stage": 11,
      "_note": "TUNE_CV_ATT (row 35R, anode) to PNP_BASES (row 36R, cathode). Vbe compensation diode." },
    { "id": "R52", "type": "R", "value": "1M",    "r1": 35, "c1": "g", "r2": 36, "c2": "pwrR", "stage": 11,
      "_note": "TUNE_CV_ATT (row 35R) to VEE (pwrR row 36, even=-12V). Current through D13 for consistent Vbe." }
  ],

  "transistors": [
    { "id": "Q9",  "subtype": "PNP", "value": "BC558",
      "eR": 10, "eC": "h", "bR": 11, "bC": "h", "cR": 12, "cC": "h", "stage": 3,
      "_note": "Accent limiter. E=ACC_NODE (row 10R), B=ACCENT_CV_IN (row 11R from J2 JPS), C=GND (row 12R, wire to pwrR). Col h, rows 10-12." },
    { "id": "Q8",  "subtype": "NPN", "value": "BC548",
      "eR": 13, "eC": "g", "bR": 10, "bC": "g", "cR": 9, "cC": "g", "stage": 3,
      "_note": "Trigger buffer. B=ACC_NODE (row 10R), C=VCC (row 9R, wire to pwrL), E=ACC_TRIG (row 13R). Col g, rows 9-10-13." },
    { "id": "Q11", "subtype": "PNP", "value": "BC558",
      "eR": 14, "eC": "i", "bR": 15, "bC": "i", "cR": 16, "cC": "i", "stage": 5,
      "_note": "Decay CV floor. E=DECAY_CAP (row 14R via JW8), B=DECAY_CV_IN (row 15R from J3 JPS), C=GND (row 16R, wire to pwrR odd). Col i, rows 14-16." },
    { "id": "Q10", "subtype": "PNP", "value": "BC558",
      "eR": 18, "eC": "d", "bR": 19, "bC": "d", "cR": 20, "cC": "d", "stage": 6,
      "_note": "XOR gate PNP. E=diode junction (row 18L), B=diode junction (row 19L), C=XOR_OUT (row 20L). Col d, rows 18-20." },
    { "id": "Q7",  "subtype": "NPN", "value": "BC548",
      "eR": 24, "eC": "c", "bR": 23, "bC": "c", "cR": 22, "cC": "c", "stage": 7,
      "_note": "HPF emitter follower. E=HPF_EMIT (row 24L), B=from C15 (row 23L), C=VCC (row 22L, wire to pwrL even). Col c, rows 22-24." },
    { "id": "Q5",  "subtype": "NPN", "value": "BC548",
      "eR": 30, "eC": "b", "bR": 29, "bC": "b", "cR": 28, "cC": "b", "stage": 9,
      "_note": "VCA NPN. B=VCA_BASE_NODE (row 29L from R40 row 28), C=row 28L (long jumper to DA2 pin 6 row 5L), E=VCA_EMIT (row 30L to R41). Changed to row 28 collector for JW6 to work. Col b, rows 28-30." },
    { "id": "Q12", "subtype": "PNP", "value": "BC558",
      "eR": 34, "eC": "b", "bR": 35, "bC": "b", "cR": 36, "cC": "b", "stage": 11,
      "_note": "Tune CV carrier PNP. E=CARRIER_TUNE_BOT (row 34L inter-board), B=PNP_BASES (row 35L from D13 via JW10), C=GND (row 36L). Col b, rows 34-36." },
    { "id": "Q13", "subtype": "PNP", "value": "BC558",
      "eR": 34, "eC": "g", "bR": 35, "bC": "g", "cR": 36, "cC": "g", "stage": 11,
      "_note": "Tune CV modulator PNP. E=MOD_TUNE_BOT (row 34R inter-board), B=PNP_BASES (row 35R shared with Q12 via JW10), C=GND (row 36R). Col g, rows 34-36." }
  ],

  "jumpers": [
    { "id": "JW1",  "r1": 7, "c1": "d",  "r2": 8, "c2": "g",  "label": "VCC→right side", "stage": 1,
      "_note": "Bring +12V from DA2 VCC net (row 7L) across gap to row 8R for R3 threshold path." },
    { "id": "JW2",  "r1": 12, "c1": "i", "r2": 13, "c2": "d", "label": "ACC_TRIG→decay", "stage": 3,
      "_note": "ACC_TRIG (Q8.E row 13R col g) to decay charge bus (row 13L). Cross sides via row 12R→row 13L." },
    { "id": "JW3",  "r1": 7, "c1": "i",  "r2": 13, "c2": "b", "label": "UNACC_TRIG out", "stage": 3,
      "_note": "UNACC_TRIG (COMP_OUT row 7R) to trigger bus (row 13L). Routes to Board 1 for VCO resets + click." },
    { "id": "JW4",  "r1": 1, "c1": "a",  "r2": 17, "c2": "a", "label": "CAR_SQ→XOR", "stage": 6,
      "_note": "Carrier square from inter-board (row 1L) down to XOR area (row 17L). Long jumper." },
    { "id": "JW5",  "r1": 2, "c1": "a",  "r2": 17, "c2": "c", "label": "MOD_SQ→XOR", "stage": 6,
      "_note": "Modulator square from inter-board (row 2L) down to XOR MOD_SQ node (row 17L). Long jumper." },
    { "id": "JW6",  "r1": 28, "c1": "b", "r2": 5, "c2": "c",  "label": "Q5.C→VCA_INV", "stage": 9,
      "_note": "Q5 collector (row 28L) to DA2 pin 6 VCA_INV (row 5L). Essential VCA connection. Long jumper." },
    { "id": "JW7",  "r1": 1, "c1": "d",  "r2": 27, "c2": "c", "label": "SINE_OUT→switch", "stage": 8,
      "_note": "SINE_OUT from inter-board (row 1L) to sine/pulse switch area (row 27L). Long jumper." },
    { "id": "JW8",  "r1": 14, "c1": "e", "r2": 14, "c2": "f", "label": "DECAY_CAP L→R", "stage": 5,
      "_note": "Bridge DECAY_CAP from left side (row 14L) to right side (row 14R) for Q11.E connection." },
    { "id": "JW9",  "r1": 6, "c1": "d",  "r2": 6, "c2": "g",  "label": "VCA_OUT bridge", "stage": 9,
      "_note": "VCA_OUT (DA2 pin 7, row 6L) across center gap to right side for output routing." },
    { "id": "JW10", "r1": 6, "c1": "j",  "r2": 33, "c2": "a", "label": "VCA_OUT→output", "stage": 9,
      "_note": "VCA_OUT from row 6R to output area (row 33L) for J5 OUTPUT jack JPS." },
    { "id": "JW11", "r1": 35, "c1": "d", "r2": 35, "c2": "f", "label": "PNP bases bridge", "stage": 11,
      "_note": "Bridge Q12 base (row 35L col b) to D13 cathode and Q13 base (row 35R). Shared PNP base node." },
    { "id": "JW12", "r1": 13, "c1": "c", "r2": 29, "c2": "c", "label": "DECAY_CAP→VCA", "stage": 9,
      "_note": "Decay envelope bus (row 13L) to VCA base area (row 29L). Envelope controls VCA gain via R40→Q5." }
  ],

  "powerWires": [
    { "r1": 7, "c1": "b",  "r2": 8,  "c2": "pwrL", "label": "DA2 VCC",       "stage": 1,
      "_note": "Pin 8 VCC (row 7L) to pwrL row 8 (even=+12V)." },
    { "r1": 4, "c1": "h",  "r2": 4,  "c2": "pwrR", "label": "DA2 VEE",       "stage": 1,
      "_note": "Pin 4 VEE (row 4R) to pwrR row 4 (even=-12V)." },
    { "r1": 3, "c1": "a",  "r2": 3,  "c2": "pwrL", "label": "GND bus L",     "stage": 1,
      "_note": "Row 3 left GND bus to pwrL row 3 (odd=GND)." },
    { "r1": 3, "c1": "j",  "r2": 3,  "c2": "pwrR", "label": "GND bus R",     "stage": 1,
      "_note": "Row 3 right GND bus to pwrR row 3 (odd=GND)." },
    { "r1": 4, "c1": "b",  "r2": 5,  "c2": "pwrL", "label": "DA2 pin5 GND",  "stage": 1,
      "_note": "DA2 pin 5 IN_B+ (row 4L) to GND (pwrL row 5, odd=GND). VCA non-inv GND reference." },
    { "r1": 9, "c1": "h",  "r2": 10, "c2": "pwrL", "label": "Q8.C VCC",      "stage": 3,
      "_note": "Q8 collector (row 9R col g) to +12V (pwrL row 10, even=+12V). Route via row 9R→pwrL." },
    { "r1": 12, "c1": "j", "r2": 13, "c2": "pwrR", "label": "Q9.C GND",      "stage": 3,
      "_note": "Q9 collector (row 12R col h) to GND (pwrR row 13, odd=GND)." },
    { "r1": 15, "c1": "a", "r2": 15, "c2": "pwrL", "label": "C3/R50 GND",    "stage": 4,
      "_note": "C3 and R50 GND ends (row 15L) to pwrL row 15 (odd=GND)." },
    { "r1": 16, "c1": "j", "r2": 17, "c2": "pwrR", "label": "Q11.C GND",     "stage": 5,
      "_note": "Q11 collector (row 16R col i) to GND (pwrR row 17, odd=GND)." },
    { "r1": 22, "c1": "a", "r2": 22, "c2": "pwrL", "label": "Q7.C VCC",      "stage": 7,
      "_note": "Q7 collector (row 22L col c) to +12V (pwrL row 22, even=+12V)." },
    { "r1": 26, "c1": "b", "r2": 26, "c2": "pwrR", "label": "HPF bias VEE",  "stage": 7,
      "_note": "R47 VEE end (row 26L) to pwrR row 26 (even=-12V). Emitter bias chain bottom." },
    { "r1": 36, "c1": "a", "r2": 35, "c2": "pwrL", "label": "Q12.C GND",     "stage": 11,
      "_note": "Q12 collector (row 36L col b) to GND (pwrL row 35, odd=GND)." },
    { "r1": 36, "c1": "h", "r2": 35, "c2": "pwrR", "label": "Q13.C GND",     "stage": 11,
      "_note": "Q13 collector (row 36R col g) to GND (pwrR row 35, odd=GND)." }
  ],

  "jpsWires": [
    { "id": "J1",     "label": "GATE IN jack",          "row": 1,  "col": "j",  "stage": 2 },
    { "id": "J2",     "label": "ACCENT CV jack",        "row": 11, "col": "i",  "stage": 3 },
    { "id": "POT2.1", "label": "DECAY pot pin1",        "row": 14, "col": "e",  "stage": 4 },
    { "id": "POT2.w", "label": "DECAY pot wiper+pin3",  "row": 16, "col": "b",  "stage": 4 },
    { "id": "J3",     "label": "DECAY CV jack",         "row": 15, "col": "j",  "stage": 5 },
    { "id": "SW2.1",  "label": "SINE/PULSE term1 (sine)", "row": 27, "col": "b", "stage": 8 },
    { "id": "SW2.c",  "label": "SINE/PULSE common",     "row": 27, "col": "d",  "stage": 8 },
    { "id": "SW2.2",  "label": "SINE/PULSE term2 (pulse)", "row": 27, "col": "i", "stage": 8 },
    { "id": "SW1.1",  "label": "FM SW term1 (MOD_TRI)",  "row": 1, "col": "g",  "stage": 10 },
    { "id": "SW1.c",  "label": "FM SW common (to Board 1)", "row": 1, "col": "f", "stage": 10 },
    { "id": "SW1.g",  "label": "FM SW term2 (GND)",     "row": 3, "col": "h",   "stage": 10 },
    { "id": "POT6.w", "label": "TUNE CV INT wiper",     "row": 34, "col": "j",  "stage": 11 },
    { "id": "J4",     "label": "TUNE CV jack",          "row": 34, "col": "g",  "stage": 11 },
    { "id": "J5",     "label": "OUTPUT jack",           "row": 33, "col": "b",  "stage": 9 }
  ],

  "netLabels": [
    { "r": 1,  "side": "L", "name": "CAR_SQ in",      "stage": 6 },
    { "r": 1,  "side": "R", "name": "GATE_IN / FM_SW", "stage": 2 },
    { "r": 2,  "side": "L", "name": "MOD_SQ in",      "stage": 6 },
    { "r": 2,  "side": "R", "name": "HP_OUT",         "stage": 2 },
    { "r": 3,  "side": "L", "name": "GND bus",        "stage": 1 },
    { "r": 3,  "side": "R", "name": "GND bus",        "stage": 1 },
    { "r": 4,  "side": "L", "name": "VCA (+) GND",    "stage": 1 },
    { "r": 4,  "side": "R", "name": "VEE",            "stage": 1 },
    { "r": 5,  "side": "L", "name": "VCA_INV (-)",    "stage": 9 },
    { "r": 5,  "side": "R", "name": "COMP (+)",       "stage": 2 },
    { "r": 6,  "side": "L", "name": "VCA_OUT",        "stage": 9 },
    { "r": 6,  "side": "R", "name": "COMP_INV (-)",   "stage": 2 },
    { "r": 7,  "side": "L", "name": "VCC",            "stage": 1 },
    { "r": 7,  "side": "R", "name": "COMP_OUT",       "stage": 2 },
    { "r": 8,  "side": "R", "name": "VCC relay",      "stage": 2 },
    { "r": 10, "side": "R", "name": "ACC_NODE",       "stage": 3 },
    { "r": 13, "side": "L", "name": "TRIG bus",       "stage": 3 },
    { "r": 13, "side": "R", "name": "ACC_TRIG",       "stage": 3 },
    { "r": 14, "side": "L", "name": "DECAY_CAP",      "stage": 4 },
    { "r": 14, "side": "R", "name": "DECAY_CAP (R)",  "stage": 5 },
    { "r": 17, "side": "L", "name": "XOR inputs",     "stage": 6 },
    { "r": 18, "side": "L", "name": "Q10.E node",     "stage": 6 },
    { "r": 19, "side": "L", "name": "Q10.B node",     "stage": 6 },
    { "r": 20, "side": "L", "name": "XOR_OUT",        "stage": 6 },
    { "r": 22, "side": "L", "name": "HPF_NODE_A",     "stage": 7 },
    { "r": 24, "side": "L", "name": "HPF_EMIT",       "stage": 7 },
    { "r": 25, "side": "L", "name": "VEE_BIAS mid",   "stage": 7 },
    { "r": 25, "side": "R", "name": "HPF_OUT",        "stage": 7 },
    { "r": 27, "side": "L", "name": "TYPE_SW_COM",    "stage": 8 },
    { "r": 27, "side": "R", "name": "SW2 pulse in",   "stage": 8 },
    { "r": 28, "side": "L", "name": "VCA_BASE",       "stage": 9 },
    { "r": 29, "side": "L", "name": "Q5.B",           "stage": 9 },
    { "r": 30, "side": "L", "name": "Q5.E",           "stage": 9 },
    { "r": 32, "side": "L", "name": "RV1 wiper",      "stage": 9 },
    { "r": 33, "side": "L", "name": "OUTPUT_J",       "stage": 9 },
    { "r": 34, "side": "L", "name": "CAR_TUNE_BOT",   "stage": 11 },
    { "r": 34, "side": "R", "name": "TUNE_CV_IN",     "stage": 11 },
    { "r": 35, "side": "L", "name": "PNP_BASES (L)",  "stage": 11 },
    { "r": 35, "side": "R", "name": "TUNE_CV_ATT",    "stage": 11 },
    { "r": 36, "side": "L", "name": "Q12 (PNP)",      "stage": 11 },
    { "r": 36, "side": "R", "name": "Q13 (PNP)",      "stage": 11 }
  ]
}
);
